#!/bin/sh

while true; do

  # Clean up previously running apps, gracefully at first then harshly
  #killall -TERM firefox-esr 2>/dev/null
  killall -TERM chromium-browser 2>/dev/null
  killall -TERM matchbox-window-manager 2>/dev/null
  sleep 2
  #killall -9 firefox-esr 2>/dev/null
  killall -9 chromium-browser 2>/dev/null
  killall -9 matchbox-window-manager 2>/dev/null

  # Clean out existing profile information
  rm -rf /home/pi/.cache
  rm -rf /home/pi/.config
  rm -rf /home/pi/.pki
  mkdir /home/pi/.config

  # Disable DPMS / Screen blanking
  xset -dpms
  xset s off
  xset s noblank
  

# Allow quitting the X server with CTRL-ATL-Backspace
setxkbmap -option terminate:ctrl_alt_bksp
# Start Chromium in kiosk mode
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
chromium-browser --start-fullscreen --kiosk --incognito --noerrdialogs --disable-translate --no-first-run --fast --fast-start --disable-infobars --disable-features=TranslateUI --disk-cache-dir=/dev/null  --password-store=basic --disable-pinch --overscroll-history-navigation=disabled --disable-features=TouchpadOverscrollHistoryNavigation "${URL}"





  ## Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
  matchbox-window-manager -use_titlebar no -use_cursor no &

  # Hide the cursor
  unclutter &

  # Start the browser
  URL="https://threatmap.checkpoint.com/" # In case the settings file doesn't exist
  test -f /home/pi/pi-display/settings.data && . /home/pi/pi-display/settings.data
  #firefox -kiosk -private-window "${URL}"
  #chromium-browser --check-for-update-interval=31536000 -app="${URL}"
done;
