#!/bin/sh

while true; do

  # Clean up previously running apps, gracefully at first then harshly
  killall -TERM firefox-esr 2>/dev/null
  killall -TERM matchbox-window-manager 2>/dev/null
  sleep 2
  killall -9 firefox-esr 2>/dev/null
  killall -9 matchbox-window-manager 2>/dev/null

  # Clean out existing profile information
  rm -rf /home/pi/.cache
  rm -rf /home/pi/.config
  rm -rf /home/pi/.pki
  mkdir /home/pi/.config

  # Disable DPMS / Screen blanking
  xset -dpms
  xset s off
  xset s noblank
  

  # Allow quitting the X server with CTRL-ATL-Backspace
  setxkbmap -option terminate:ctrl_alt_bksp



  ## Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
  matchbox-window-manager -use_titlebar no -use_cursor no &

  # Hide the cursor
  unclutter &

  # Start the browser
  URL="https://threatmap.checkpoint.com/" # In case the settings file doesn't exist
  if test -f /home/pi/pi-display/settings.data; then
    echo "Obtaining url from settings"
    URL=$(cat /home/pi/pi-display/settings.data | grep "URL=" | cut -d  "=" -f 2-)
  else
    echo "Could not find settings, using default url: ${URL}"
  fi
  firefox -kiosk -private-window "${URL}"
  #chromium-browser --check-for-update-interval=31536000 -app="${URL}"
done;
